### ISSUE TITLE
Why minSDK 24?

### ISSUE THREAD

**Issue by licaon-kter** [spacecowboy/Feeder#13]

**Comment by spacecowboy** [comment]
It is the minimum version you can use in order to make use of Java8 syntax

**Comment by ebraminio** [comment]
Jack compiler that you have enabled allows compile to older versions also only without any change, only if you are using j8 specific packages that won't AFAIK which I didn't check.

**Comment by spacecowboy** [comment]
https://developer.android.com/guide/platform/j8-jack.html

The page isn't very clear on this but essentially the Java8 Stream APIs are Android24 and up only. The same goes for `java.util.Optional`. So these are the lines that require SDK24:

* https://github.com/spacecowboy/Feeder/blob/1.2.2/app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.java#L81

* https://github.com/spacecowboy/Feeder/blob/1.2.2/app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.java#L118

* https://github.com/spacecowboy/Feeder/blob/1.2.2/app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.java#L123

* https://github.com/spacecowboy/Feeder/blob/1.2.2/app/src/main/java/com/nononsenseapps/feeder/model/RssLocalSync.java#L134

![selection_001](https://cloud.githubusercontent.com/assets/223655/24081138/4c6e5e62-0cad-11e7-9ca0-7405222478eb.png)

**Comment by ebraminio** [comment]
This makes sense, thanks for investigating.

Just generally speaking--I am not in favor of making people to stick with older version of languages at all, which is painful IMO, and I don't use Android and RSS feeds much nowadays honestly--but I've found jack compiler very unstable at least on my setup, I guess that is particularly when it is used beside proguard as it perhaps interferes with SAM main methods naming which possibly makes perhaps pre-built libraries unable to work properly, just wanted to share my experience on it.

**Comment by spacecowboy** [comment]
Yeah I've seen some issues as well - in particular very long compile times. But it won't be an issue for long since Jack was recently deprecated: https://android-developers.googleblog.com/2017/03/future-of-java-8-language-feature.html
