### ISSUE TITLE
Feeder app/repo in 'grey text' / non-clickable / downloadable at F-Droid ?

### ISSUE THREAD

**Issue by fenix011** [spacecowboy/Feeder#18]
Hi @spacecowboy , when i was about to enjoy _Feeder_ , tried ot install : it it appears to me repo in 'grey text' / non-clickable / downloadable at F-Droid ? I'm probably missing some very basics here... and i wonder, what is it ?

**Comment by spacecowboy** [comment]
Hmm. Maybe your Android version is too old? It requires Android 5.0 at least.

**Comment by jordila** [comment]
Ah... you're right. Mine is v.4.4.4 .
      
      On 30/03/17 14:53, Jonas Kalderstam wrote:
    
    
      Hmm. Maybe your Android version is too old? It requires Android
        5.0 at least.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/spacecowboy/Feeder","title":"spacecowboy/Feeder","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/spacecowboy/Feeder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@spacecowboy in #18: Hmm. Maybe your Android version is too old? It requires Android 5.0 at least."}],"action":{"name":"View Issue","url":"https://github.com/spacecowboy/Feeder/issues/18#issuecomment-290401399"}}}
    
    
    
    
    -- 
jordila_
