### ISSUE TITLE
"There  was a problem while parsing the package"

### ISSUE THREAD

**Issue by fenix011** [spacecowboy/Feeder#19]
Hi again, While trying to circumvent my previously reported issue #18 
i tried to download the .apk , and got that error message :+1: 

> "There  was a problem while parsing the package"

What are we missing here ?
regards

### Context :
_Feeder APK_ v1.2.2
_Android Linux version_ : 4.4.4

**Comment by spacecowboy** [comment]
Your Android version is too old. Feeder requires Android 5.0
