### ISSUE TITLE
Excessive Battery Usage

### ISSUE THREAD

**Issue by Trevonn** [spacecowboy/Feeder#24]
I'm guessing it's due syncing in the background. Maybe an option to manually sync or change the default time interval would be better

Nexus 5x, Android 7.1.1

**Comment by spacecowboy** [comment]
Agree completely. Next version will have some settings.

Initial work done here: https://github.com/spacecowboy/Feeder/commit/f9f8ceac28bbd8ab43a8d56718b65dfb9a169dfc

Also here: https://github.com/spacecowboy/Feeder/pull/23

**Comment by spacecowboy** [comment]
This should be the final nail in this coffin: https://github.com/spacecowboy/Feeder/pull/25
