### ISSUE TITLE
Open drawer after hitting fab button to mark all articles read

### ISSUE THREAD

**Issue by Matth7878** [spacecowboy/Feeder#375]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.6.32

### Where did you get the app from

Other

### Feature or improvement you want

It would a great QOL improvment if when hitting fab button to mark all read then drawer was opened. You could then choose another tag to continue reading.

### Why should this be added?

When you mark all articles read you end up on an empty screen where there is nothing to do. To continue reading articles from others tags the only choice is to manually open the drawer.
So it would be nice for users if it was opening without having to do it manually to continue reading or to check if other tags with unread article exists.

**Comment by sweetman-zz** [comment]
As a suggestion in the same thread I just see that other apps (Feedly) jumps automatically to the next drawer when you mark all feeds read.
Then, when you click the last drawer and no more feeds are available, just display the actual message (select another drawer add content).
Tony

**Comment by spacecowboy** [comment]
I think it could be a nice feature.

It could be an setting, but doesn't have to be.

I think this would be a good first issue to work on too.

**Comment by spacecowboy** [comment]
> > As a suggestion in the same thread I just see that other apps (Feedly) jumps automatically to the next drawer when you mark all feeds read.
> 
> If this option exists it would be nice to be a different setting. I don't read tagged categories alphabetically. Next tag I am reading depends on how many unread articles exists and what interests me more.

This feature is about opening the navigation drawer when the fab is pressed, nothing more

**Comment by maksimowiczm** [comment]
Sorry for off-topic.

While working on the issue, I noticed that you're using a custom navigation drawer. This implementation isn't perfect and comes with some strange behavior (I'm not sure if it's intended) such as allowing the feed to be scrolled while the drawer is open.

I assume that at the time of implementation, the `androidx.compose.material3` version was not yet available. Do you plan on migrating to the [compose navigation drawer](https://developer.android.com/develop/ui/compose/components/drawer)?

**Comment by AlbertoFabbri93** [comment]
I think the "mark all as read" button should not open the drawer when the user is in the "all feeds" tab. Open the drawer in that case is useless as all the other tabs are empty as well.

**Comment by Lyndeno** [comment]
> I think the "mark all as read" button should not open the drawer when the user is in the "all feeds" tab. Open the drawer in that case is useless as all the other tabs are empty as well.

I agree

**Comment by spacecowboy** [comment]
> I think the "mark all as read" button should not open the drawer when the user is in the "all feeds" tab. Open the drawer in that case is useless as all the other tabs are empty as well.

Could be a reasonable exception yes. Please open a new feature request for that
