### ISSUE TITLE
Feeds break when adding feeds via the floating action button

### ISSUE THREAD

**Issue by NHodgesVFX** [spacecowboy/Feeder#385]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.6.33

### Where did you get the app from

Other

### Android version

GrapheneOS build 2024100800

### Device model

Pixel 9 Pro XL

### First occurred

Today, only started using the app today

### Steps to reproduce

Note: you may need to perform the steps a couple times.

1. Have a couple of previously added feeds
2. Add a RSS feed using the floating action button
3. Look at the feeds list by clicking the hamburger icon in the top left corner
4. Notice some feeds no longer have posts
5. If you click into that feed, it asks you to open a feed or add a feed

### Expected behaviour

Feed is added and other previously added feeds continue to work

### Current behaviour

Some feeds lose their posts, refreshing doesn't work for the affected feeds. The only way to fix it is by deleting and re-adding the affected feed.

This issue only occurs when using the floating action button adding feeds from the 3 dots menu in the top right corner works fine.

**Comment by spacecowboy** [comment]
You need to change your filter. You've marked the articles as read.

Change to show read articles

**Comment by spacecowboy** [comment]
The floating action button doesn't add feeds. It marks all articles in list as read

**Comment by NHodgesVFX** [comment]
Ah that makes sense. Thanks for letting me know.
