### ISSUE TITLE
Support muted feeds

### ISSUE THREAD

**Issue by shuvashish76** [spacecowboy/Feeder#390]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.6.32

### Where did you get the app from

F-Droid

### Feature or improvement you want

Add support for mute/unmute as follows:
 - Long press any feed/folder & mute/unmute from there
 - Show mute/unmute feeds for all folders as a whole, from settings
 - Option to either _hide_ or _display_ muted sites from settings for your "Feed page"

### Why should this be added?

Usecase: This feature will be useful incase you do not want some site feeds as your regular default feed but you only check their headlines/important new articles occasionally, for which you have to manually go to that particular feed & click reload.

Another usecase would be muting my town's recreation feed. They post ~10x things a day, burying my actual news. I would rather check their feed whenever I feel like doing something in town.

### Screenshots / Drawings / Technical details

Idea inspired from [newsblur](https://github.com/samuelclay/NewsBlur)
![newsblur-mute-sites](https://user-images.githubusercontent.com/48226312/233079850-eb8a95a3-09f9-4c51-ad8e-9032906a0dbd.png)

**Comment by spacecowboy** [comment]
This will not be implemented.

Use tags to organize your feeds. Move spammy tags into their own tag(s) and group more important feeds together.

**Comment by xan2622** [comment]
I was just making a mock-up image when I found this suggestion. I also hope that users will be able to temporary disable RSS feeds.

<img src="https://github.com/user-attachments/assets/46dba3f2-34ca-4f2c-be70-e6a35601b115" width="50%" height="50%">
