### ISSUE TITLE
Missing icon in feed's list

### ISSUE THREAD

**Issue by christop69** [spacecowboy/Feeder#404]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.6.33

### Where did you get the app from

Google Play

### Android version

14

### Device model

Samsung A55

### Steps to reproduce

Some feeds don't have an icon (it's not about the dark theme with an all black icon, it's the same with the white theme). How explain ? Would it be possible to choose and force one ?

Example of feed without icon : https://www.begeek.fr/feed

![Screenshot_20241029_093939_Feeder](https://github.com/user-attachments/assets/a1e05080-52d6-47fb-be7e-de5266b75b1b)

**Comment by spacecowboy** [comment]
Not a bug. The site simply doesn't have an icon defined on their site.

Feeder uses either the favicon or the apple-...-icon one.

**Comment by christop69** [comment]
I a not an expert in favicon but begeek.fr seems to have one if I test with http://www.google.com/s2/favicons?domain=begeek.fr 

Any idea ?

<img width="128" alt="firefox_ZM2zXuUP8d" src="https://github.com/user-attachments/assets/25a1a611-9861-4998-a4df-208840629010">

**Comment by spacecowboy** [comment]
no idea

**Comment by christop69** [comment]
Possible bug ? So maybe you could reopen the issue ?

**Comment by spacecowboy** [comment]
No.

I looked at the feed. It doesn't link to the HTML site. Only itself.

So feeder can't know what the site address is.

**Comment by christop69** [comment]
OK I understand for begeek

One last point and I'll stop bothering you ^^ :

For lesnumeriques.com the feed is 

<link rel="alternate" type="text/html" href="https://www.lesnumeriques.com/"/>
<link rel="self" type="application/atom+xml" href="https://www.lesnumeriques.com/rss.xml"/>
<updated>2024-11-03T15:03:22+01:00</updated>
<id>https://www.lesnumeriques.com/</id>
<icon>
https://cdn.lesnumeriques.com/optim/images/favicon-LN-rss.png
</icon>
<logo>
https://cdn.lesnumeriques.com/optim/images/logo-LN-rss.png
</logo>

The link seems to be OK ? But the icon that's displayed (ugly) isn't that of the link or of the “icon” tag, but that of the “logo” tag, it seems ?

**Comment by spacecowboy** [comment]
Yes. That's the one which is picked.

**Comment by christop69** [comment]
> Yes. That's the one which is picked.

Don't you think it would be more appropriate to choose the icon tag ? Or ideally to give the user the choice when adding the feed ?

**Comment by spacecowboy** [comment]
There is nothing saying that one will be of higher quality than the other.

And no, I don't think users should get to pick.
