### ISSUE TITLE
Allow unlimited max items per feed

### ISSUE THREAD

**Issue by bremyozo** [spacecowboy/Feeder#410]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.6.33

### Where did you get the app from

F-Droid

### Feature or improvement you want

Allow setting **Max items per feed** higher than 1000

### Why should this be added?

If you're unable to  look at a feed that can have 100+ items per day for extended period of time or for long term storage

### Screenshots / Drawings / Technical details

Having unlimited option or custom - when selected let the user input desired number of items - or both

**Comment by spacecowboy** [comment]
Unlimited means Feeder would happily consume all storage on your device and never delete any data.

My answer is no
