### ISSUE TITLE
If a specific Feed is selected the App always defaults to that specific feed as opposed to my main tag "News"

### ISSUE THREAD

**Issue by polo421** [spacecowboy/Feeder#420]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.6.33

### Where did you get the app from

Google Play

### Android version

Android 15

### Device model

Pixel 9 Pro XL

### First occurred

Always 

### Steps to reproduce

1. Add several feeds under one tag
2. Select a specific feed 
3. Close app
4. Open app and you always only be seeing that specific feed until you change back the main tag

### Expected behaviour

I would like for the app to always go back to the main tag of all my feeds. That should be the default view. Maybe this could be a setting that makes it where the app has a default view and it can be toggled  from "where I left off" to "always go to tag x" etc etc. 

### Current behaviour

App will continue to open to a specific feed until a different feed or tag is chosen.

**Comment by spacecowboy** [comment]
Feeder opens the last feed/tag you opened last time.

**Comment by polo421** [comment]
So I've had some time to observe it more and for some reason the app is changing to a different feed on its own. I don't use the app in a way to change feeds at all. I just want to see my main tag "News" with my 4 total feeds all shown together in my only tag. But I find myself in specific feeds sometimes and I don't even know it until I've noticed that haven't seen articles from certain feeds in a while and look up and I'm in a specific feed instead of my main tag. 

So there may be reasons why you want this behavior but if not I will continue to give my thought on why this is happening. One is possibly when I click the notification of a new article and there is exactly only 1 new unread. Then the app behaves differently (than if there were over 2) and is setting the view now to that specific feed that had the 1 unread article. That or when there is an unread article and you open the app it automatically opens a specific feed. I feel like when I have multiple unread notifications, the app behaves perfectly and never changes the view. My issue seems to only happen when there is 1 unread notification. I'm not sure though. I just know I've used the app a pretty long time and I don't have any reason to change that feed/tag view and it happens maybe once every day or so. Hopefully you can clarify what is going on. 

Regardless, thanks for the awesome communication and amazing app. I've tried every app for RSS in existence and you guys are the best by mile 👍

**Comment by polo421** [comment]
Hello, I never really got a reply after my message. I just wanted to update again and say that I am still having issues with this. I find the app takes me to a specific feed sometimes when opening a notification and then I am stuck in that feed view until I notice I have t seen articles from other feeds in a while. I am missing a lot of new articles because of this. My ideal behavior would be to have a setting to set either "All Feeds" as the default view always or to have the ability to set a sub folder as the default view. Thank you.

**Comment by spacecowboy** [comment]
This is working as intended. Feeder remembers what you opened last time.

Just swipe from the left and change to All Feeds again
