### ISSUE TITLE
Mark As Read does nothing

### ISSUE THREAD

**Issue by doommoose43** [spacecowboy/Feeder#427]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.7.0

### Where did you get the app from

Google Play

### Android version

14

### Steps to reproduce

1. Open up app
2. Have unread articles in list
3. Using any method (long-press and mark above/below as read, tapping the mark all as read button on the lower right-hand corner of the screen, opening the three-dot menu and tapping mark as read, sliding an article to mark it as read, etc ), attempt to mark an article(s) as read

### Expected behaviour

Article disappears from unread article list.

### Current behaviour

List remains unchanged; article is not marked as read.

**Comment by RaelRo** [comment]
Same bug on my phone.

**Comment by Lyndeno** [comment]
Also experiencing this. Pressing the mark all as read bubble opens the side menu

**Comment by RMHogervorst** [comment]
Version 2.7.0 android 14, ndroid security  update A October 1, 2024. Vendor security level September 5, 2024.

**Comment by RMHogervorst** [comment]
Possibly related https://github.com/spacecowboy/Feeder/issues/425
