### ISSUE TITLE
Get AI summary with Perplexity AI 

### ISSUE THREAD

**Issue by emilw74** [spacecowboy/Feeder#430]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.7.0

### Where did you get the app from

Google Play

### Feature or improvement you want

Get Feeder integrated with Perplexity in order to be able to generate articles summaries. The same way as it is integrated now with Open AI via API Key.

**Comment by spacecowboy** [comment]
This should already be possible in latest version thanks to https://github.com/spacecowboy/Feeder/pull/399 since Perplexity offers an OpenAPI compatible API.

You need to configure the API Url to point to perplexity's, and then add their Api Key. It's all in the perplexity documentation.

**Comment by emilw74** [comment]
I looked up Perplexity API documentation, provided correct API Key and pointed out to proper url: https://api.perplexity.ai/

But now I am getting an error in Feeder API set-up screen:

Unable to load models. No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class com.aallam.openai.api.exception.OpenAIError
with response from https://api.perplexity.ai/models:
status: 404
response headers:
cf-cache-status: DYNAMIC
, cf-ray: 8e6cbe58bcc3eecd-WAW
, content-length: 0
, content-type: text/plain; charset=utf-8
, date: Fri, 22 Nov 2024 23:36:46 GMT
, server: cloudflare
, set-cookie: __cf_bm=o9AVFUulOzEN4UpUVscAF3tfORgwa_oEVYXLJtngV_E-1732318606-1.0.1.1-YeIZh9lzRQEiQtAbyNcCJZAeD8wwyxvHyNHhUHw_rE71cmBs7L98JRteYygxTNzxlo6VjPO507pvyxfAcX0T2w; path=/; expires=Sat, 23-Nov-24 00:06:46 GMT; domain=.perplexity.ai; HttpOnly; Secure; SameSite=None

**Comment by emilw74** [comment]
I looked up Perplexity API documentation, provided correct API Key and pointed out to proper url: https://api.perplexity.ai/

But now I am getting an error in Feeder API set-up screen:

_Unable to load models. No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class com.aallam.openai.api.exception.OpenAIError
with response from https://api.perplexity.ai/models:
status: 404
response _headers:
cf-cache-status: DYNAMIC
, cf-ray: 8e6cbe58bcc3eecd-WAW
, content-length: 0
, content-type: text/plain; charset=utf-8
, date: Fri, 22 Nov 2024 23:36:46 GMT_
, server: cloudflare_

Still I disregarded this error massage and tried to setup manually several different Model IDs recommended by Perplexity API documentation but then each time I tried to generate an article summary, I was getting this massage instead:

[_"At body -> response_format -> ResponseFormatText -> type: Input should be 'text'", "At body -> response_format -> ResponseFormatJSONSchema -> type: Input should be 'json_schema'", "At body -> response_format -> ResponseFormatJSONSchema -> json_schema: Field required", "At body -> response_format -> ResponseFormatRegex -> type: Input should be 'regex'", "At body -> response_format -> ResponseFormatRegex -> regex: Field required"]_

**Comment by emilw74** [comment]
@anod Any idea if this is relatively easy doable?

**Comment by anod** [comment]
I've used json format for summary to return language as part of the response, otherwise it would provide a summary on a random language. looks like Perplexity API doesn't support json_object return type, I will check other options

**Comment by emilw74** [comment]
> I will check other options

Great, than you

**Comment by emilw74** [comment]
Very fast turnaround - thank you! 
@spacecowboy when are you planning to publish updated version?

**Comment by spacecowboy** [comment]
> Very fast turnaround - thank you! @spacecowboy when are you planning to publish updated version?

I usually try to time releases to weekends. but I can release whenever

**Comment by emilw74** [comment]
> I usually try to time releases to weekends. but I can release whenever

OK, got it 👌

**Comment by emilw74** [comment]
New version available now, tested and works perfectly - thank you! 

My suggested set-up In "Open Ai" settings within Feeder App, for those being Perplexity Pro users:

**API Key**: _get your individual API Key from Perplexity settings in section "API" (at the very bottom)_ 
**Model**: llama-3.1-sonar-huge-128k-online
**URL link**: https://api.perplexity.ai/
**Azure ID**: _keep empty_
**Azure API:** _keep empty_

The model suggested above seems the right balance between speed of reply and quality of generated summaries
