### ISSUE TITLE
Can't mark articles read

### ISSUE THREAD

**Issue by BHydden** [spacecowboy/Feeder#442]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

Version 2.7.1  com.nononsenseapps.feeder.play versionCode 320

### Where did you get the app from

Google Play

### Android version

Android 15 GrapheneOS 2024120400

### Device model

Pixel 6

### First occurred

4 weeks ago

### Steps to reproduce

1. Open app 
2. Open several articles, any feed
3. See that all articles remain in the feed, as if unread
4. Click the "mark all as read" button
5. Instead of clearing the feed, button just opens the LH slide menu to show all feeds

### Expected behaviour

Read articles should not be visible, or at least be visibly distinct from unread articles

### Current behaviour

Nothing changes, all articles look the same whether read or not

**Comment by spacecowboy** [comment]
Change your filter to not show read items then.

![Screenshot_20241206_073117_Feeder](https://github.com/user-attachments/assets/ae1744e8-5592-4aa3-8d10-2c51af526385)

**Comment by BHydden** [comment]
Oh, lol... thank you 👍 fixed. No idea how that got turned on 🤔

**Comment by spacecowboy** [comment]
I recently changed the default. Sorry about that

**Comment by BHydden** [comment]
All good, glad I asked haha, I probably should have looked for a filter before assuming it was a bug, especially since nobody else was reporting it. Thanks for the quick reply.

**Comment by businessBoris** [comment]
So if I read an item and then somehow lose the page etc I have to go through a whole rigmarole to get to the link again? As opposed to the previous behaviour where it sits there greyed out.

Whereas to get the new default behaviour one only had to refresh the display. Pull the top down. 

That doesn't help usability, but it's your app.
