### ISSUE TITLE
Add Lookup frequency "Every 5 minutes"

### ISSUE THREAD

**Issue by NourEddineX** [spacecowboy/Feeder#452]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same feature request.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
- [X] I will describe the problem with as much detail as possible.
- [X] This request contains only one single feature, **not** a list of multiple (related) features.

### App version

2.7.1

### Where did you get the app from

F-Droid

### Feature or improvement you want

Add Lookup frequency "Every 5 minutes"

### Why should this be added?

RSS is widely used to follow urgent events that require quick response

**Comment by spacecowboy** [comment]
As has been mentioned in other feature requests, the minimum is 15 minutes and that is enforced by Android.


https://developer.android.com/develop/background-work/background-tasks/persistent/getting-started/define-work
