### ISSUE TITLE
Clicking a group of new post notifications (from multiple feeds) sometimes takes you to a random feed view as opposed to "All Feeds" or a subfolder of feeds. The app then locks you into that specific feed until you go back to "All Feeds" etc. 

### ISSUE THREAD

**Issue by polo421** [spacecowboy/Feeder#457]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.7.1

### Where did you get the app from

Google Play

### Android version

15

### Device model

Pixel 7 Pro

### First occurred

Always

### Steps to reproduce

1. Have multiple feeds setup for new post notifications 
2. Wait for a group of new notifications 
3. Click on the notification
4. Intermittently, the app will open to a seemingly random feed view as opposed to "All Feeds"

### Expected behaviour

There should be a way to receive notifications for just "All Feeds" or a specific subfolder of feeds. Then clicking those  new notifications will always open to either All Feeds or the subfolder chosen for notifications. 

### Current behaviour

Upon clicking on the group of new notifications, the App intermittently opens to a seemingly random feed and upon doing so, the app will now be stuck (by design) in that feed view until All Feeds etc is selected. Personally, I do not ever click on specific feeds as part of my flow so I do not ever want to be in a specific feed. The only time I notice that I am in a specific feed is when I realize I am missing articles from other feeds.

**Comment by spacecowboy** [comment]
Please stop opening bugs. This is not a bug as I've explained. I consider your behavior to be quite rude.

If you want to suggest a feature then open a feature request.

**Comment by polo421** [comment]
You closed the other thread saying when you select a feed that the app will keep you in that feed view until you select a new one. I accept that is the intended behavior and with the way that bug report was reported, it should be closed. But I also think the app going to different feed views on its own is a separate bug. I've never selected a different feed view besides all feeds and the app still throws me into specific feed views once a day (if I use notifications). I'm not trying to be rude, I'm trying to help fix a problem with as clear a way of communicating I know how. If you are reading a rude tone, I can assure you that is not where I can coming from. I'm sorry if that is how it came out. 

If you wish to clarify anything I've said with some follow up questions, I'm more than willing to discuss this further to make sure I am explaining things correctly.

**Comment by polo421** [comment]
Again, i really don't know how else to do describe the behavior I've seen other than a bug. 

As an example, I have new post notifications setup for 5 different feeds. If all 5 different feeds post a new notification at the same time and I click on it on that one notification, sometimes the app will just randomly choose one of those feed views and only show me those articles. In my opinion, if you click a notification from multiple different feeds then it should go to the "All Feeds" view. I hope that makes sense.

**Comment by spacecowboy** [comment]
If you click on a notification that contains multiple articles, Feeder will try to open the specific feed/tag. That is the moment when you picked a different feed.

**Comment by spacecowboy** [comment]
> Ok thank you. Hopefully you guys will consider one day giving us an option to make sure it stays in the same feed view. I went ahead and turned off notifications for now and just check the app periodically. Regardless, thank you for the clarification.

Maybe you aren't understanding me. If you want this *feature*, please go ahead and open a *feature request* here on github. When you create a new issue you get to pick if it's a bug or a feature request.
