### ISSUE TITLE
Update spinner obscuring top headline

### ISSUE THREAD

**Issue by europrobe** [spacecowboy/Feeder#463]
### Checklist

- [X] I have used the search function for [**OPEN**](https://github.com/spacecowboy/feeder/issues) issues to see if someone else has already submitted the same bug report.
- [X] I have **also** used the search function for [**CLOSED**](https://github.com/spacecowboy/feeder/issues?q=is%3Aissue+is%3Aclosed) issues to see if the problem is already solved and just waiting to be released.
- [X] I will describe the problem with as much detail as possible.
- [X] If the bug only to occurs with a certain feed, I will include the URL of that feed.

### App version

2.7.1

### Where did you get the app from

Google Play

### Android version

15

### Device model

pixel 8

### First occurred

since ever 

### Steps to reproduce

1. Pull down in the feed list to force an update
2. Watch the spinner appear and obscure the top headline. 
3. Get annoyed since you wanted to browse the existing headlines while waiting for any new articles to load. 
4. Bonus: Watch the spinner disappear but remain unsure whether there were any new articles. 
5. Pull down again to check if any new articles have loaded.
6. Wish for a better indication, any would in fact do, that new articles have appeared.

### Expected behaviour

Not obscure the top headline
Make some visible indication of any new articles

**Comment by spacecowboy** [comment]
This is not a bug. Please open a feature request (select feature request when you open an issue)
